# Generated by Django 3.2.5 on 2021-07-12 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qmeshi_app', '0002_alter_item_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='tag',
            field=models.CharField(max_length=32, verbose_name='種類'),
        ),
    ]
