# Generated by Django 3.2.5 on 2021-07-10 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qmeshi_app', '0002_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menu',
            field=models.TextField(blank=True, max_length=1024, verbose_name='メニュー'),
        ),
    ]
