# Generated by Django 3.2.5 on 2021-07-12 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qmeshi_app', '0003_alter_menu_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cafeteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='食堂名')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='アイテム')),
            ],
        ),
        migrations.RemoveField(
            model_name='impression',
            name='book',
        ),
        migrations.AlterField(
            model_name='impression',
            name='comment',
            field=models.TextField(blank=True, max_length=1024, verbose_name='コメント'),
        ),
        migrations.AddField(
            model_name='impression',
            name='item',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='impressions', to='qmeshi_app.item', verbose_name='アイテム'),
            preserve_default=False,
        ),
    ]
