# Generated by Django 3.2.5 on 2021-07-12 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qmeshi_app', '0005_cafeteria_short_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
