# Generated by Django 3.2.5 on 2021-07-13 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qmeshi_app', '0008_cafeteria_table_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafeteria',
            name='priority',
            field=models.IntegerField(default=1, verbose_name='表示優先度'),
        ),
        migrations.AddField(
            model_name='tag',
            name='priority',
            field=models.IntegerField(default=1, verbose_name='表示優先度'),
        ),
    ]
