# Generated by Django 3.2.5 on 2021-07-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qmeshi_app', '0009_auto_20210713_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafeteria',
            name='opening_hours',
            field=models.CharField(default='-', max_length=128, verbose_name='営業時間'),
        ),
    ]
